/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizquimica.view;

/**
 *
 * @author Angela
 */
public class DashboardAlunoNovo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAlunoNovo.class.getName());

    /**
     * Creates new form DashboardAlunoNovo
     */
    public DashboardAlunoNovo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        painelTopo = new javax.swing.JPanel();
        lblTituloTopo = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        lblTituloQuizzes = new javax.swing.JLabel();
        linhaTituloQuizzes = new javax.swing.JPanel();
        cardExperimentos = new javax.swing.JPanel();
        lblTextoExperimentos = new javax.swing.JLabel();
        btnParticiparExperimentos = new javax.swing.JButton();
        lblIconeExperimentos = new javax.swing.JLabel();
        cardMateriaisLab = new javax.swing.JPanel();
        lblTextoMateriaisLab = new javax.swing.JLabel();
        btnParticiparMateriaisLab = new javax.swing.JButton();
        lblIconeMateriaisLab = new javax.swing.JLabel();
        cardSeguranca = new javax.swing.JPanel();
        lblTextoEquipamentos = new javax.swing.JLabel();
        lblTextoSeguranca = new javax.swing.JLabel();
        btnParticiparSeguranca = new javax.swing.JButton();
        lblIconeSeguranca = new javax.swing.JLabel();
        linhaDivisoria = new javax.swing.JPanel();
        lblTituloDesempenho = new javax.swing.JLabel();
        linhaTituloDesempenho = new javax.swing.JPanel();
        cardDesempenho = new javax.swing.JPanel();
        lblTituloAcertos = new javax.swing.JLabel();
        progressAcertos = new javax.swing.JProgressBar();
        progressErros = new javax.swing.JProgressBar();
        progressProgresso = new javax.swing.JProgressBar();
        lblTituloErros = new javax.swing.JLabel();
        lblTituloProgresso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QuiZmica - Painel do Aluno");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelFundo.setBackground(new java.awt.Color(238, 246, 252));
        painelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/quizmicamenor.png"))); // NOI18N
        painelFundo.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        painelTopo.setBackground(new java.awt.Color(179, 0, 0));
        painelTopo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloTopo.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        lblTituloTopo.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTopo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTopo.setText("Painel do aluno");
        painelTopo.add(lblTituloTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 15, 310, 45));

        btnSair.setBackground(new java.awt.Color(179, 0, 0));
        btnSair.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("↪  Sair");
        btnSair.setFocusPainted(false);
        painelTopo.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 18, 150, 40));

        painelFundo.add(painelTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 75));

        lblTituloQuizzes.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTituloQuizzes.setForeground(new java.awt.Color(35, 45, 60));
        lblTituloQuizzes.setText("Seus quizzes:");
        painelFundo.add(lblTituloQuizzes, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 190, 300, 40));

        linhaTituloQuizzes.setBackground(new java.awt.Color(179, 0, 0));

        javax.swing.GroupLayout linhaTituloQuizzesLayout = new javax.swing.GroupLayout(linhaTituloQuizzes);
        linhaTituloQuizzes.setLayout(linhaTituloQuizzesLayout);
        linhaTituloQuizzesLayout.setHorizontalGroup(
            linhaTituloQuizzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        linhaTituloQuizzesLayout.setVerticalGroup(
            linhaTituloQuizzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        painelFundo.add(linhaTituloQuizzes, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 230, 70, 2));

        cardExperimentos.setBackground(new java.awt.Color(255, 255, 255));
        cardExperimentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoExperimentos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTextoExperimentos.setForeground(new java.awt.Color(35, 45, 60));
        lblTextoExperimentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoExperimentos.setText("Experimentos Químicos");
        cardExperimentos.add(lblTextoExperimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 78, 190, 55));

        btnParticiparExperimentos.setBackground(new java.awt.Color(5, 68, 75));
        btnParticiparExperimentos.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btnParticiparExperimentos.setForeground(new java.awt.Color(255, 255, 255));
        btnParticiparExperimentos.setText("▷ Participar");
        btnParticiparExperimentos.setFocusPainted(false);
        cardExperimentos.add(btnParticiparExperimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 200, 35));

        lblIconeExperimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/experimentos.png"))); // NOI18N
        cardExperimentos.add(lblIconeExperimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, -1, -1));

        painelFundo.add(cardExperimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 200, 210));

        cardMateriaisLab.setBackground(new java.awt.Color(255, 255, 255));
        cardMateriaisLab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoMateriaisLab.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTextoMateriaisLab.setForeground(new java.awt.Color(35, 45, 60));
        lblTextoMateriaisLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoMateriaisLab.setText("Materiais do laboratório");
        cardMateriaisLab.add(lblTextoMateriaisLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 78, 190, 55));

        btnParticiparMateriaisLab.setBackground(new java.awt.Color(5, 68, 75));
        btnParticiparMateriaisLab.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btnParticiparMateriaisLab.setForeground(new java.awt.Color(255, 255, 255));
        btnParticiparMateriaisLab.setText("▷ Participar");
        btnParticiparMateriaisLab.setFocusPainted(false);
        cardMateriaisLab.add(btnParticiparMateriaisLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 200, 35));

        lblIconeMateriaisLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/vidrarias.png"))); // NOI18N
        cardMateriaisLab.add(lblIconeMateriaisLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, -1, -1));

        painelFundo.add(cardMateriaisLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 260, 200, 210));

        cardSeguranca.setBackground(new java.awt.Color(255, 255, 255));
        cardSeguranca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoEquipamentos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTextoEquipamentos.setForeground(new java.awt.Color(35, 45, 60));
        lblTextoEquipamentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoEquipamentos.setText("Equipamentos de");
        cardSeguranca.add(lblTextoEquipamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, 55));

        lblTextoSeguranca.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTextoSeguranca.setForeground(new java.awt.Color(35, 45, 60));
        lblTextoSeguranca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoSeguranca.setText("Segurança");
        cardSeguranca.add(lblTextoSeguranca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 55));

        btnParticiparSeguranca.setBackground(new java.awt.Color(5, 68, 75));
        btnParticiparSeguranca.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btnParticiparSeguranca.setForeground(new java.awt.Color(255, 255, 255));
        btnParticiparSeguranca.setText("▷ Participar");
        btnParticiparSeguranca.setFocusPainted(false);
        cardSeguranca.add(btnParticiparSeguranca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 200, 35));

        lblIconeSeguranca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/materiaisSeguranca.png"))); // NOI18N
        cardSeguranca.add(lblIconeSeguranca, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, -1, -1));

        painelFundo.add(cardSeguranca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 200, 210));

        linhaDivisoria.setBackground(new java.awt.Color(150, 160, 170));

        javax.swing.GroupLayout linhaDivisoriaLayout = new javax.swing.GroupLayout(linhaDivisoria);
        linhaDivisoria.setLayout(linhaDivisoriaLayout);
        linhaDivisoriaLayout.setHorizontalGroup(
            linhaDivisoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        linhaDivisoriaLayout.setVerticalGroup(
            linhaDivisoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        painelFundo.add(linhaDivisoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 130, 3, 590));

        lblTituloDesempenho.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTituloDesempenho.setText("Seu desempenho:");
        painelFundo.add(lblTituloDesempenho, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 350, 40));

        linhaTituloDesempenho.setBackground(new java.awt.Color(179, 0, 0));

        javax.swing.GroupLayout linhaTituloDesempenhoLayout = new javax.swing.GroupLayout(linhaTituloDesempenho);
        linhaTituloDesempenho.setLayout(linhaTituloDesempenhoLayout);
        linhaTituloDesempenhoLayout.setHorizontalGroup(
            linhaTituloDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        linhaTituloDesempenhoLayout.setVerticalGroup(
            linhaTituloDesempenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        painelFundo.add(linhaTituloDesempenho, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 230, 70, 2));

        cardDesempenho.setBackground(new java.awt.Color(255, 255, 255));
        cardDesempenho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloAcertos.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloAcertos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloAcertos.setForeground(new java.awt.Color(35, 45, 60));
        lblTituloAcertos.setText("Acertos:");
        cardDesempenho.add(lblTituloAcertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 45, 200, 35));

        progressAcertos.setBackground(new java.awt.Color(210, 210, 210));
        progressAcertos.setForeground(new java.awt.Color(30, 190, 90));
        progressAcertos.setValue(60);
        progressAcertos.setStringPainted(true);
        cardDesempenho.add(progressAcertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 95, 400, 35));

        progressErros.setBackground(new java.awt.Color(210, 210, 210));
        progressErros.setForeground(new java.awt.Color(230, 60, 60));
        progressErros.setValue(10);
        progressErros.setStringPainted(true);
        cardDesempenho.add(progressErros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 400, 35));

        progressProgresso.setForeground(new java.awt.Color(0, 100, 230));
        progressProgresso.setValue(70);
        progressProgresso.setStringPainted(true);
        cardDesempenho.add(progressProgresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 325, 400, 35));

        lblTituloErros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloErros.setForeground(new java.awt.Color(35, 45, 60));
        lblTituloErros.setText("Erros: ");
        cardDesempenho.add(lblTituloErros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 200, 35));

        lblTituloProgresso.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTituloProgresso.setText("Progresso:");
        cardDesempenho.add(lblTituloProgresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 275, 250, 35));

        painelFundo.add(cardDesempenho, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 245, 500, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/etecRedimensionada.png"))); // NOI18N
        painelFundo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 100, 80));

        getContentPane().add(painelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAlunoNovo().setVisible(true));
    }
    
    public javax.swing.JButton getBtnParticiparExperimentos() {
    return btnParticiparExperimentos;
    }

    public javax.swing.JButton getBtnParticiparMateriaisLab() {
    return btnParticiparMateriaisLab;
    }

    public javax.swing.JButton getBtnParticiparSeguranca() {
    return btnParticiparSeguranca;
    }

    public javax.swing.JButton getBtnSair() {
    return btnSair;
    }

    public javax.swing.JProgressBar getProgressAcertos() {
    return progressAcertos;
    }

    public javax.swing.JProgressBar getProgressErros() {
    return progressErros;
    }

    public javax.swing.JProgressBar getProgressProgresso() {
    return progressProgresso;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnParticiparExperimentos;
    private javax.swing.JButton btnParticiparMateriaisLab;
    private javax.swing.JButton btnParticiparSeguranca;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel cardDesempenho;
    private javax.swing.JPanel cardExperimentos;
    private javax.swing.JPanel cardMateriaisLab;
    private javax.swing.JPanel cardSeguranca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIconeExperimentos;
    private javax.swing.JLabel lblIconeMateriaisLab;
    private javax.swing.JLabel lblIconeSeguranca;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTextoEquipamentos;
    private javax.swing.JLabel lblTextoExperimentos;
    private javax.swing.JLabel lblTextoMateriaisLab;
    private javax.swing.JLabel lblTextoSeguranca;
    private javax.swing.JLabel lblTituloAcertos;
    private javax.swing.JLabel lblTituloDesempenho;
    private javax.swing.JLabel lblTituloErros;
    private javax.swing.JLabel lblTituloProgresso;
    private javax.swing.JLabel lblTituloQuizzes;
    private javax.swing.JLabel lblTituloTopo;
    private javax.swing.JPanel linhaDivisoria;
    private javax.swing.JPanel linhaTituloDesempenho;
    private javax.swing.JPanel linhaTituloQuizzes;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JPanel painelTopo;
    private javax.swing.JProgressBar progressAcertos;
    private javax.swing.JProgressBar progressErros;
    private javax.swing.JProgressBar progressProgresso;
    // End of variables declaration//GEN-END:variables
}
