/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizquimica.view;

/**
 *
 * @author Angela
 */
public class DesempenhoAluno extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DesempenhoAluno.class.getName());
    private String nomeAluno;
    /**
     * Creates new form DesempenhoAluno
     */
    public DesempenhoAluno(java.awt.Frame parent, String nomeAluno) {
        initComponents();
        setLocationRelativeTo(null);
        this.nomeAluno = nomeAluno;
        lblNomeAluno.setText(nomeAluno);

        lblQuizzesConcluidos.setText("-");
        lblMediaGeral.setText("-");
        lblMelhorPontuacao.setText("-");
        lblAcertosTotais.setText("-");
        lblErrosTotais.setText("-");
        lblTaxaAcerto.setText("-");
        lblQuizzesRealizados.setText("-");
            
            javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblHistorico.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{"Quiz", "Pontuação", "Dicas Usadas", "Ações"});
        model.addRow(new Object[]{"Carregando histórico...", "", "", ""});

        jToggleButton1.addActionListener(e -> {
            MenuProfessor menu = new MenuProfessor(this, true);
            menu.setLocationRelativeTo(this);
            menu.setVisible(true);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lblTitutloPagina = new javax.swing.JLabel();
        lblSubtituloPagina = new javax.swing.JLabel();
        cardAluno = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        lblNomeAluno = new javax.swing.JLabel();
        lblTurmaAluno = new javax.swing.JLabel();
        miniCardQuizzes = new javax.swing.JPanel();
        lblTituloQuizzes = new javax.swing.JLabel();
        lblQuizzesConcluidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        miniCardMedia = new javax.swing.JPanel();
        lblTituloMedia = new javax.swing.JLabel();
        lblMediaGeral = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        miniCardMelhor = new javax.swing.JPanel();
        lblTituloMelhor = new javax.swing.JLabel();
        lblMelhorPontuacao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cardResumo = new javax.swing.JPanel();
        lblTituloResumo = new javax.swing.JLabel();
        lblTituloRealizados = new javax.swing.JLabel();
        lblAcertosTotais = new javax.swing.JLabel();
        lblTituloErros = new javax.swing.JLabel();
        lblErrosTotais = new javax.swing.JLabel();
        lblTituloAcertos1 = new javax.swing.JLabel();
        lblTaxaAcerto = new javax.swing.JLabel();
        lblTituloTaxa1 = new javax.swing.JLabel();
        lblQuizzesRealizados = new javax.swing.JLabel();
        linhaResumo1 = new javax.swing.JPanel();
        linhaResumo2 = new javax.swing.JPanel();
        linhaResumo3 = new javax.swing.JPanel();
        cardHistorico = new javax.swing.JPanel();
        lblTituloHistorico = new javax.swing.JLabel();
        scrollHistorico = new javax.swing.JScrollPane();
        tblHistorico = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quizmica - Desempenho do Aluno");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelFundo.setBackground(new java.awt.Color(238, 243, 249));
        painelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/quizmicamenor.png"))); // NOI18N
        painelFundo.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 150));

        btnVoltar.setBackground(new java.awt.Color(238, 243, 249));
        btnVoltar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(179, 40, 36));
        btnVoltar.setText(" ←  VOLTAR");
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setFocusPainted(false);
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);
        painelFundo.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 150, 160, 35));

        lblTitutloPagina.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitutloPagina.setForeground(new java.awt.Color(20, 25, 45));
        lblTitutloPagina.setText("Desempenho do Aluno");
        painelFundo.add(lblTitutloPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 500, 40));

        lblSubtituloPagina.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubtituloPagina.setForeground(new java.awt.Color(70, 80, 100));
        lblSubtituloPagina.setText("Acompanhe o desempenho individual dos alunos nos quizzes.");
        painelFundo.add(lblSubtituloPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 650, 25));

        cardAluno.setBackground(new java.awt.Color(255, 255, 255));
        cardAluno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAvatar.setBackground(new java.awt.Color(235, 220, 255));
        lblAvatar.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblAvatar.setForeground(new java.awt.Color(120, 60, 210));
        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setText("AM");
        lblAvatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAvatar.setOpaque(true);
        cardAluno.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 32, 70, 70));

        lblNomeAluno.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblNomeAluno.setForeground(new java.awt.Color(20, 20, 30));
        lblNomeAluno.setText("Ana Maria Silva");
        cardAluno.add(lblNomeAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 38, 300, 30));

        lblTurmaAluno.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblTurmaAluno.setForeground(new java.awt.Color(70, 80, 100));
        lblTurmaAluno.setText("Turma: 2° Química A");
        cardAluno.add(lblTurmaAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 72, 300, 30));

        miniCardQuizzes.setBackground(new java.awt.Color(238, 243, 255));
        miniCardQuizzes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloQuizzes.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTituloQuizzes.setForeground(new java.awt.Color(20, 20, 30));
        lblTituloQuizzes.setText("Quizzes Realizados");
        miniCardQuizzes.add(lblTituloQuizzes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 20));

        lblQuizzesConcluidos.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblQuizzesConcluidos.setForeground(new java.awt.Color(0, 100, 230));
        lblQuizzesConcluidos.setText("01 ");
        miniCardQuizzes.add(lblQuizzesConcluidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 130, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 100, 230));
        jLabel1.setText("✓");
        miniCardQuizzes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 40, 40));

        cardAluno.add(miniCardQuizzes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 250, 70));

        miniCardMedia.setBackground(new java.awt.Color(235, 250, 240));
        miniCardMedia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloMedia.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTituloMedia.setForeground(new java.awt.Color(20, 20, 30));
        lblTituloMedia.setText("Média Geral");
        miniCardMedia.add(lblTituloMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 20));

        lblMediaGeral.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblMediaGeral.setForeground(new java.awt.Color(0, 140, 60));
        lblMediaGeral.setText("78 %");
        miniCardMedia.add(lblMediaGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 120, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 140, 60));
        jLabel2.setText("↗");
        miniCardMedia.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 22, 40, 40));

        cardAluno.add(miniCardMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 250, 70));

        miniCardMelhor.setBackground(new java.awt.Color(255, 248, 235));
        miniCardMelhor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloMelhor.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTituloMelhor.setForeground(new java.awt.Color(150, 80, 0));
        lblTituloMelhor.setText("Melhor Pontuação");
        miniCardMelhor.add(lblTituloMelhor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 20));

        lblMelhorPontuacao.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblMelhorPontuacao.setForeground(new java.awt.Color(230, 130, 0));
        lblMelhorPontuacao.setText("95 %");
        miniCardMelhor.add(lblMelhorPontuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 130, 0));
        jLabel3.setText("☆");
        miniCardMelhor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 18, 40, 40));

        cardAluno.add(miniCardMelhor, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 250, 70));

        painelFundo.add(cardAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 1280, 130));

        cardResumo.setBackground(new java.awt.Color(255, 255, 255));
        cardResumo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloResumo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTituloResumo.setForeground(new java.awt.Color(20, 25, 45));
        lblTituloResumo.setText("Resumo de Desempenho");
        cardResumo.add(lblTituloResumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 25));

        lblTituloRealizados.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTituloRealizados.setForeground(new java.awt.Color(20, 25, 45));
        lblTituloRealizados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRealizados.setText("Quizzes Realizados");
        cardResumo.add(lblTituloRealizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 250, 20));

        lblAcertosTotais.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblAcertosTotais.setForeground(new java.awt.Color(0, 140, 60));
        lblAcertosTotais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcertosTotais.setText("12");
        cardResumo.add(lblAcertosTotais, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        lblTituloErros.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTituloErros.setForeground(new java.awt.Color(20, 25, 45));
        lblTituloErros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloErros.setText("Erros Totais");
        cardResumo.add(lblTituloErros, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 250, 20));

        lblErrosTotais.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblErrosTotais.setForeground(new java.awt.Color(190, 0, 0));
        lblErrosTotais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrosTotais.setText("7");
        cardResumo.add(lblErrosTotais, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 50, -1));

        lblTituloAcertos1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTituloAcertos1.setForeground(new java.awt.Color(20, 25, 45));
        lblTituloAcertos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloAcertos1.setText("Acertos Totais");
        cardResumo.add(lblTituloAcertos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 250, 20));

        lblTaxaAcerto.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTaxaAcerto.setForeground(new java.awt.Color(0, 100, 230));
        lblTaxaAcerto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaxaAcerto.setText("60 %");
        cardResumo.add(lblTaxaAcerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, -1, -1));

        lblTituloTaxa1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTituloTaxa1.setForeground(new java.awt.Color(20, 25, 45));
        lblTituloTaxa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTaxa1.setText("Taxa de Acerto");
        cardResumo.add(lblTituloTaxa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 250, 20));

        lblQuizzesRealizados.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblQuizzesRealizados.setForeground(new java.awt.Color(60, 70, 90));
        lblQuizzesRealizados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuizzesRealizados.setText("1");
        cardResumo.add(lblQuizzesRealizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, -1, -1));

        linhaResumo1.setBackground(new java.awt.Color(220, 225, 235));

        javax.swing.GroupLayout linhaResumo1Layout = new javax.swing.GroupLayout(linhaResumo1);
        linhaResumo1.setLayout(linhaResumo1Layout);
        linhaResumo1Layout.setHorizontalGroup(
            linhaResumo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        linhaResumo1Layout.setVerticalGroup(
            linhaResumo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        cardResumo.add(linhaResumo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 8, 1, 65));

        linhaResumo2.setBackground(new java.awt.Color(220, 225, 235));

        javax.swing.GroupLayout linhaResumo2Layout = new javax.swing.GroupLayout(linhaResumo2);
        linhaResumo2.setLayout(linhaResumo2Layout);
        linhaResumo2Layout.setHorizontalGroup(
            linhaResumo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        linhaResumo2Layout.setVerticalGroup(
            linhaResumo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        cardResumo.add(linhaResumo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 8, 1, 65));

        linhaResumo3.setBackground(new java.awt.Color(220, 225, 235));

        javax.swing.GroupLayout linhaResumo3Layout = new javax.swing.GroupLayout(linhaResumo3);
        linhaResumo3.setLayout(linhaResumo3Layout);
        linhaResumo3Layout.setHorizontalGroup(
            linhaResumo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        linhaResumo3Layout.setVerticalGroup(
            linhaResumo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        cardResumo.add(linhaResumo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(948, 8, 1, 65));

        painelFundo.add(cardResumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 1280, 80));

        cardHistorico.setBackground(new java.awt.Color(255, 255, 255));
        cardHistorico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloHistorico.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTituloHistorico.setForeground(new java.awt.Color(20, 25, 45));
        lblTituloHistorico.setText("Histórico de Quizzes");
        cardHistorico.add(lblTituloHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 350, 25));

        tblHistorico.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        tblHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Materiais do laboratório", "", "", "DETALHES"},
                {"Experimentos Químicos", "", null, "DETALHES"},
                {"Equipamentos de Segurança", null, null, "DETALHES"}
            },
            new String [] {
                "Quiz", "Pontuação", "Dicas Usadas", "Ações"
            }
        ));
        tblHistorico.setRowHeight(32);
        scrollHistorico.setViewportView(tblHistorico);

        cardHistorico.add(scrollHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 1240, 210));

        painelFundo.add(cardHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 1280, 260));

        jPanel20.setBackground(new java.awt.Color(179, 40, 36));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Alunos");
        jPanel20.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 510, 40));

        jToggleButton1.setBackground(new java.awt.Color(179, 40, 36));
        jToggleButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("☰");
        jToggleButton1.setToolTipText("");
        jToggleButton1.setBorder(null);
        jPanel20.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 100, 60));

        painelFundo.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 75));

        getContentPane().add(painelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DesempenhoAluno(null, "Teste").setVisible(true));    }

    public javax.swing.JButton getBtnVoltar() {
      return btnVoltar;
    }
    public javax.swing.JLabel getLblAvatar() {
       return lblAvatar;
    }

    public javax.swing.JLabel getLblNomeAluno() {
       return lblNomeAluno;
    }
    public javax.swing.JLabel getLblTurmaAluno() {
       return lblTurmaAluno;
    }
    public javax.swing.JLabel getLblQuizzesConcluidos() {
       return lblQuizzesConcluidos;
    }
    public javax.swing.JLabel getLblMediaGeral() {
       return lblMediaGeral;
    }
    public javax.swing.JLabel getLblMelhorPontuacao() {
       return lblMelhorPontuacao;
    }
    public javax.swing.JLabel getLblAcertosTotais() {
       return lblAcertosTotais;
    }

    public javax.swing.JLabel getLblErrosTotais() {
       return lblErrosTotais;
    }

    public javax.swing.JLabel getLblTaxaAcerto() {
       return lblTaxaAcerto;
    }

    public javax.swing.JLabel getLblQuizzesRealizados() {
       return lblQuizzesRealizados;
    }

    public javax.swing.JTable getTblHistorico() {
        return tblHistorico;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel cardAluno;
    private javax.swing.JPanel cardHistorico;
    private javax.swing.JPanel cardResumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblAcertosTotais;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblErrosTotais;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMediaGeral;
    private javax.swing.JLabel lblMelhorPontuacao;
    private javax.swing.JLabel lblNomeAluno;
    private javax.swing.JLabel lblQuizzesConcluidos;
    private javax.swing.JLabel lblQuizzesRealizados;
    private javax.swing.JLabel lblSubtituloPagina;
    private javax.swing.JLabel lblTaxaAcerto;
    private javax.swing.JLabel lblTituloAcertos1;
    private javax.swing.JLabel lblTituloErros;
    private javax.swing.JLabel lblTituloHistorico;
    private javax.swing.JLabel lblTituloMedia;
    private javax.swing.JLabel lblTituloMelhor;
    private javax.swing.JLabel lblTituloQuizzes;
    private javax.swing.JLabel lblTituloRealizados;
    private javax.swing.JLabel lblTituloResumo;
    private javax.swing.JLabel lblTituloTaxa1;
    private javax.swing.JLabel lblTitutloPagina;
    private javax.swing.JLabel lblTurmaAluno;
    private javax.swing.JPanel linhaResumo1;
    private javax.swing.JPanel linhaResumo2;
    private javax.swing.JPanel linhaResumo3;
    private javax.swing.JPanel miniCardMedia;
    private javax.swing.JPanel miniCardMelhor;
    private javax.swing.JPanel miniCardQuizzes;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JScrollPane scrollHistorico;
    private javax.swing.JTable tblHistorico;
    // End of variables declaration//GEN-END:variables
}
