/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package quizquimica.view;

/**
 *
 * @author Angela
 */

import quizquimica.controller.PopUpPrimeiroAcessoController;
import quizquimica.model.Usuario;


public class PopUpPrimeiroAcesso extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PopUpPrimeiroAcesso.class.getName());

    /**
     * Creates new form PopUpPrimeiroAcesso
     */
    public PopUpPrimeiroAcesso(java.awt.Frame parent, boolean modal) {
     this(parent, modal, null);
    }

    public PopUpPrimeiroAcesso(java.awt.Frame parent, boolean modal, Usuario usuario) {
     super(parent, modal);
     initComponents();

     setSize(850, 600);
     setLocationRelativeTo(parent);
     setResizable(false);

     setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

     addWindowListener(new java.awt.event.WindowAdapter() {
      @Override
      public void windowClosing(java.awt.event.WindowEvent e) {
        javax.swing.JOptionPane.showMessageDialog(
                PopUpPrimeiroAcesso.this,
                "Para continuar, você precisa redefinir sua senha."
        );
      }
     });

     configurarVisual();

     new PopUpPrimeiroAcessoController(this, usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        linhaVermelha = new javax.swing.JPanel();
        lblFrasco = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblTextoExplicativo = new javax.swing.JLabel();
        lblTextoExplicativo1 = new javax.swing.JLabel();
        lblNovaSenha = new javax.swing.JLabel();
        txtNovaSenha = new javax.swing.JPasswordField();
        lblConfirmarSenha = new javax.swing.JLabel();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        painelAviso = new javax.swing.JPanel();
        lblIconeAviso = new javax.swing.JLabel();
        lblAtencao = new javax.swing.JLabel();
        lblTextoAviso = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvarContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Primeiro acesso");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelFundo.setBackground(new java.awt.Color(255, 255, 255));
        painelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/quiZmicaSimplificado.png"))); // NOI18N
        painelFundo.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 15, 280, 85));

        linhaVermelha.setBackground(new java.awt.Color(179, 40, 36));

        javax.swing.GroupLayout linhaVermelhaLayout = new javax.swing.GroupLayout(linhaVermelha);
        linhaVermelha.setLayout(linhaVermelhaLayout);
        linhaVermelhaLayout.setHorizontalGroup(
            linhaVermelhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        linhaVermelhaLayout.setVerticalGroup(
            linhaVermelhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        painelFundo.add(linhaVermelha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 690, 4));

        lblFrasco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrasco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/bequerAcesso.png"))); // NOI18N
        painelFundo.add(lblFrasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 290, 350));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(20, 25, 45));
        lblTitulo.setText("Seja muito bem-vindo(a) ao QuiZmica!");
        painelFundo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 150, 450, 35));

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblSubtitulo.setText("É um prazer te ter aqui.");
        painelFundo.add(lblSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 350, 25));

        lblTextoExplicativo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTextoExplicativo.setForeground(new java.awt.Color(51, 51, 51));
        lblTextoExplicativo.setText("Como este é o seu primeiro acesso,");
        painelFundo.add(lblTextoExplicativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 230, 430, 55));

        lblTextoExplicativo1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTextoExplicativo1.setForeground(new java.awt.Color(51, 51, 51));
        lblTextoExplicativo1.setText("redefina sua senha para continuar.");
        painelFundo.add(lblTextoExplicativo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 255, 430, 55));

        lblNovaSenha.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNovaSenha.setForeground(new java.awt.Color(20, 25, 45));
        lblNovaSenha.setText("Nova senha:");
        painelFundo.add(lblNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 320, 160, 20));

        txtNovaSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNovaSenha.setForeground(new java.awt.Color(20, 25, 45));
        txtNovaSenha.setText("jPasswordField1");
        txtNovaSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 120, 120)));
        painelFundo.add(txtNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 338, 420, 35));

        lblConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblConfirmarSenha.setForeground(new java.awt.Color(20, 25, 45));
        lblConfirmarSenha.setText("Confirmar nova senha:");
        painelFundo.add(lblConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 380, 180, 20));

        txtConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConfirmarSenha.setForeground(new java.awt.Color(20, 25, 45));
        txtConfirmarSenha.setText("jPasswordField1");
        txtConfirmarSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 120, 120)));
        painelFundo.add(txtConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 400, 420, 35));

        painelAviso.setBackground(new java.awt.Color(255, 246, 214));
        painelAviso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 184, 45)));
        painelAviso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconeAviso.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        lblIconeAviso.setForeground(new java.awt.Color(241, 184, 45));
        lblIconeAviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconeAviso.setText("!");
        painelAviso.add(lblIconeAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 35, 40));

        lblAtencao.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblAtencao.setForeground(new java.awt.Color(51, 51, 51));
        lblAtencao.setText("Atenção: ");
        painelAviso.add(lblAtencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 5, -1, -1));

        lblTextoAviso.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTextoAviso.setForeground(new java.awt.Color(51, 51, 51));
        lblTextoAviso.setText("não esqueça essa senha.");
        painelAviso.add(lblTextoAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 5, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Ela será usada nos próximos acessos.");
        painelAviso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 20, -1, -1));

        painelFundo.add(painelAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 445, 300, 45));

        btnSalvarContinuar.setBackground(new java.awt.Color(179, 40, 36));
        btnSalvarContinuar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalvarContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarContinuar.setText("Salvar e continuar");
        btnSalvarContinuar.setBorderPainted(false);
        btnSalvarContinuar.setFocusPainted(false);
        btnSalvarContinuar.setOpaque(true);
        painelFundo.add(btnSalvarContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 505, 330, 45));

        getContentPane().add(painelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarVisual() {
    painelFundo.setBackground(new java.awt.Color(255, 255, 255));

    linhaVermelha.setBackground(new java.awt.Color(179, 40, 36));

    lblTitulo.setForeground(new java.awt.Color(20, 25, 45));
    lblSubtitulo.setForeground(new java.awt.Color(51, 51, 51));
    lblTextoExplicativo.setForeground(new java.awt.Color(51, 51, 51));

    lblNovaSenha.setForeground(new java.awt.Color(20, 25, 45));
    lblConfirmarSenha.setForeground(new java.awt.Color(20, 25, 45));

    txtNovaSenha.setBackground(new java.awt.Color(255, 255, 255));
    txtNovaSenha.setForeground(new java.awt.Color(20, 25, 45));
    txtNovaSenha.setBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 120, 120), 1)
    );

    txtConfirmarSenha.setBackground(new java.awt.Color(255, 255, 255));
    txtConfirmarSenha.setForeground(new java.awt.Color(20, 25, 45));
    txtConfirmarSenha.setBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 120, 120), 1)
    );

    painelAviso.setBackground(new java.awt.Color(255, 246, 214));
    painelAviso.setBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 184, 45), 1)
    );

    lblIconeAviso.setForeground(new java.awt.Color(241, 184, 45));
    lblTextoAviso.setForeground(new java.awt.Color(51, 51, 51));

    btnSalvarContinuar.setBackground(new java.awt.Color(179, 40, 36));
    btnSalvarContinuar.setForeground(new java.awt.Color(255, 255, 255));
    btnSalvarContinuar.setOpaque(true);
    btnSalvarContinuar.setBorderPainted(false);
    btnSalvarContinuar.setFocusPainted(false);
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PopUpPrimeiroAcesso dialog = new PopUpPrimeiroAcesso(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarContinuar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAtencao;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblFrasco;
    private javax.swing.JLabel lblIconeAviso;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNovaSenha;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTextoAviso;
    private javax.swing.JLabel lblTextoExplicativo;
    private javax.swing.JLabel lblTextoExplicativo1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel linhaVermelha;
    private javax.swing.JPanel painelAviso;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JPasswordField txtNovaSenha;
    // End of variables declaration//GEN-END:variables


    public javax.swing.JPasswordField getTxtNovaSenha() {
    return txtNovaSenha;
    }

    public javax.swing.JPasswordField getTxtConfirmarSenha() {
    return txtConfirmarSenha;
    }

    public javax.swing.JButton getBtnSalvarContinuar() {
    return btnSalvarContinuar;
    }
}
