/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package quizquimica.view;

/**
 *
 * @author Angela
 */
public class PopUpDicaQuiz extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PopUpDicaQuiz.class.getName());

    /**
     * Creates new form PopUpDicaQuiz
     */
    public PopUpDicaQuiz(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        configurarCampoDica();
        configurarEventos();

        setLocationRelativeTo(parent);
    }

    private void configurarCampoDica() {
    txtDica.setEditable(false);
    txtDica.setEnabled(true);

    txtDica.setLineWrap(true);
    txtDica.setWrapStyleWord(true);

    txtDica.setOpaque(false);
    txtDica.setBackground(new java.awt.Color(255, 255, 255));
    txtDica.setForeground(new java.awt.Color(40, 40, 40));
    txtDica.setDisabledTextColor(new java.awt.Color(40, 40, 40));
    txtDica.setBorder(null);

    txtDica.setFocusable(false);
    }

    private void configurarEventos() {
    btnFechar.addActionListener(e -> dispose());
    }

    public void setDadosDica(String nomePersonagem, String descricaoPersonagem, String textoDica) {
    lblNomePersonagem.setText(nomePersonagem);
    lblDescricaoPersonagem.setText(descricaoPersonagem);
    txtDica.setText(textoDica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        lblImagemPersonagem = new javax.swing.JLabel();
        painelDescricaoPersonagem = new javax.swing.JPanel();
        lblDescricaoPersonagem = new javax.swing.JLabel();
        cardDica = new javax.swing.JPanel();
        scrollDica = new javax.swing.JScrollPane();
        txtDica = new javax.swing.JTextArea();
        painelNomePersonagem = new javax.swing.JPanel();
        lblNomePersonagem = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dica");
        setMinimumSize(new java.awt.Dimension(520, 330));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelFundo.setBackground(new java.awt.Color(238, 246, 252));
        painelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagemPersonagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagemPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/CurieRedimensionada.png"))); // NOI18N
        painelFundo.add(lblImagemPersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, 210));

        painelDescricaoPersonagem.setBackground(new java.awt.Color(232, 232, 232));
        painelDescricaoPersonagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescricaoPersonagem.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lblDescricaoPersonagem.setForeground(new java.awt.Color(150, 150, 150));
        lblDescricaoPersonagem.setText("Pioneira da radioatividade");
        painelDescricaoPersonagem.add(lblDescricaoPersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 3, 240, 25));

        painelFundo.add(painelDescricaoPersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 110, 270, 32));

        cardDica.setBackground(new java.awt.Color(255, 255, 255));
        cardDica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollDica.setBackground(new java.awt.Color(255, 255, 255));
        scrollDica.setBorder(null);
        scrollDica.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtDica.setColumns(20);
        txtDica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDica.setForeground(new java.awt.Color(40, 40, 40));
        txtDica.setLineWrap(true);
        txtDica.setRows(5);
        txtDica.setText("“Esse material é usado para aquecer substâncias em laboratório.”");
        txtDica.setWrapStyleWord(true);
        scrollDica.setViewportView(txtDica);

        cardDica.add(scrollDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, 330, 85));

        painelFundo.add(cardDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 375, 125));

        painelNomePersonagem.setBackground(new java.awt.Color(179, 0, 0));
        painelNomePersonagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomePersonagem.setBackground(new java.awt.Color(255, 255, 255));
        lblNomePersonagem.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblNomePersonagem.setForeground(new java.awt.Color(255, 255, 255));
        lblNomePersonagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomePersonagem.setText("MARIE CURIE");
        painelNomePersonagem.add(lblNomePersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 260, 40));

        painelFundo.add(painelNomePersonagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 77, 300, 50));

        btnFechar.setBackground(new java.awt.Color(238, 246, 252));
        btnFechar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(179, 0, 0));
        btnFechar.setText("X");
        btnFechar.setBorderPainted(false);
        btnFechar.setContentAreaFilled(false);
        btnFechar.setFocusPainted(false);
        btnFechar.addActionListener(this::btnFecharActionPerformed);
        painelFundo.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 35, 30));

        getContentPane().add(painelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PopUpDicaQuiz dialog = new PopUpDicaQuiz(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JPanel cardDica;
    private javax.swing.JLabel lblDescricaoPersonagem;
    private javax.swing.JLabel lblImagemPersonagem;
    private javax.swing.JLabel lblNomePersonagem;
    private javax.swing.JPanel painelDescricaoPersonagem;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JPanel painelNomePersonagem;
    private javax.swing.JScrollPane scrollDica;
    private javax.swing.JTextArea txtDica;
    // End of variables declaration//GEN-END:variables
}
