import quizquimica.controller.JogarController;

public class TelaJogar extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAluno
     */
    public TelaJogar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BotaoJogar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BotaoProfessor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TermoUso = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/Quizmica 2 sem fundo 1.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quizmica");
        setBackground(new java.awt.Color(230, 240, 251));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(238, 243, 249));
        jPanel3.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/quizmica titulo.png"))); // NOI18N
        jPanel3.setBounds(20, 10, 300, 120);
        jPanel3.add(jPanel1);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Misture ideias. Descubra respostas.");
        jPanel3.add(jLabel4);

        BotaoJogar.setBackground(new java.awt.Color(179, 40, 36));
        BotaoJogar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BotaoJogar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoJogar.setText("JOGAR");
        BotaoJogar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray));
        BotaoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoJogarActionPerformed(evt);
            }
        });
        jPanel3.add(BotaoJogar);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/etec - cópia.png"))); // NOI18N
        jPanel3.add(jLabel5);

        BotaoProfessor.setBackground(new java.awt.Color(102, 102, 102));
        BotaoProfessor.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        BotaoProfessor.setForeground(new java.awt.Color(255, 255, 255));
        BotaoProfessor.setText("Acesso do professor");
        BotaoProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoProfessorActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizquimica/images/imageminicial.png"))); // NOI18N
        jPanel3.add(jLabel3);

        TermoUso.setFont(new java.awt.Font("Arial", 2, 9)); // NOI18N
        TermoUso.setForeground(new java.awt.Color(102, 102, 102));
        TermoUso.setText("Termo de Uso");
        TermoUso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TermoUsoMouseClicked(evt);
            }
        });
        jPanel3.add(TermoUso);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoJogarActionPerformed(java.awt.event.ActionEvent evt) {
        JogarController controller = new JogarController(this);
        controller.abrirLogin();
    }//GEN-LAST:event_BotaoJogarActionPerformed

    private void BotaoProfessorActionPerformed(java.awt.event.ActionEvent evt) {
        JogarController controller = new JogarController(this);
        controller.abrirLogin();
    }//GEN-LAST:event_BotaoProfessorActionPerformed

    private void TermoUsoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TermoUsoMouseClicked
        JogarController controller = new JogarController(this);
        controller.abrirTermos();

    }//GEN-LAST:event_TermoUsoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogar.class.getName());
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogar.class.getName());
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogar.class.getName());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogar.class.getName());
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoJogar;
    private javax.swing.JButton BotaoProfessor;
    private javax.swing.JLabel TermoUso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
